apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myserver-dwsurvey
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myserver-dwsurvey
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
              #averageUtilization: 80
              #type: Utilization
        averageValue: 500Mi
        type: AverageValue
