apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myserver-dwsurvey
spec:
  maxReplicas: 300
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myserver-dwsurvey
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageUtilization: 50
        type: Utilization
        #averageValue: 5000Mi
        #type: AverageValue
