apiVersion: apps/v1
kind: Deployment
metadata:
  name: myserver-dwsurvey
spec:
  selector:
    matchLabels:
      run: myserver-dwsurvey
  template:
    metadata:
      labels:
        run: myserver-dwsurvey
    spec:
      containers:
      - name: myserver-dwsurvey
        #image: harbor.example.local/hpa/hpa-example:latest
        #image: myserver-zzh-cn-north-1.jcr.service.jdcloud.com/hpa-example:latest
        image: myserver-zzh-cn-north-1.jcr.service.jdcloud.com/dwsurvey:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:                                 #控制器资源限制
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 200Mi
