apiVersion: apps/v1
kind: Deployment
metadata:
  name: myserver-dwsurvey
spec:
  selector:
    matchLabels:
      run: myserver-dwsurvey
  template:
    metadata:
      labels:
        run: myserver-dwsurvey
    spec:
      containers:
      - name: myserver-dwsurvey
        #image: harbor.example.local/hpa/hpa-example:latest
        #image: myserver-zzh-cn-north-1.jcr.service.jdcloud.com/hpa-example:latest
        image: myserver-zzh-cn-north-1.jcr.service.jdcloud.com/dwsurvey:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:                                 #控制器资源限制
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service                                  #创建一个svc
metadata:
  name: myserver-dwsurvey 
  labels:
    run: myserver-dwsurvey
spec:
  type: NodePort
  ports:
    - port: 80          #服务访问端口
      targetPort: 8080    #对应容器端口
      nodePort: 31080   #NodePort
  selector:
    run: myserver-dwsurvey
