apiVersion: v1
kind: Service                                  #创建一个svc
metadata:
  name: myserver-dwsurvey
  labels:
    run: myserver-dwsurvey
spec:
  type: NodePort
  ports:
    - port: 80          #服务访问端口
      targetPort: 8080    #对应容器端口
      nodePort: 31080   #NodePort
  selector:
    run: myserver-dwsurvey
