apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    #app.kubernetes.io/name: mysql
data:
  primary.cnf: |                   #配置master
    [mysqld]
    log-bin                        #master激活二进制日志
  replica.cnf: |                   #配置slave
    [mysqld]
    super-read-only                 #slave权限为只读
